abstract class Routes {
  static const profile = _Paths.profile;
  static const editProfile = _Paths.editProfile;
  static const reminder = _Paths.reminder;
  static const splash = _Paths.splash;
  static const onboarding = _Paths.onboarding;
  static const questionnaire = _Paths.questionnaire;
  static const startQuestionnaire = _Paths.startQuestionnaire;
  static const cameraAnalysis = _Paths.cameraAnalysis;
  static const startCamera = _Paths.startCamera;
  static const assessmentResult = _Paths.assessmentResult;
  static const navigation = _Paths.navigation;
  static const home = _Paths.home;
  static const specialists = _Paths.specialists;
  static const specialistProfile = _Paths.specialistProfile;
  static const success = _Paths.success;
  static const words = _Paths.words;
  static const srartwords = _Paths.srartwords;
  static const breathing = _Paths.breathing;
  static const srartexercise = _Paths.srartexercise;
  static const payment = _Paths.payment;
  static const plan = _Paths.plan;
  static const auth = _Paths.auth;
  static const login = _Paths.login;
  static const signup = _Paths.signup;
  static const forgetPassword = _Paths.forgetPassword;
  static const otp = _Paths.otp;
  static const changePassword = _Paths.changePassword;
  static const space = _Paths.space;
  static const groups = _Paths.groups;
  static const avilableGroup = _Paths.avilableGroup;
  Routes._();
}

abstract class _Paths {
  static const profile = '/profile';
  static const editProfile = '/editProfile';
  static const reminder = '/reminder';
  static const splash = '/splash';
  static const onboarding = '/onboarding';
  static const questionnaire = '/questionnaire';
  static const startQuestionnaire = '/startQuestionnaire';
  static const cameraAnalysis = '/cameraAnalysis';
  static const startCamera = '/startCamera';
  static const assessmentResult = '/assessmentResult';
  static const navigation = '/navigation';
  static const home = '/home';
  static const specialists = '/specialists';
  static const specialistProfile = '/specialistProfile';
  static const success = '/success';
  static const words = '/words';
  static const srartwords = '/srartwords';
  static const breathing = '/breathing';
  static const srartexercise = '/srartexercise';
  static const payment = '/payment';
  static const plan = '/plan';
  static const forgetPassword = '/forget_password';
  static const auth = '/auth';
  static const login = '/login';
  static const signup = '/signup';
  static const otp = '/otp';
  static const changePassword = '/change_password';
  static const space = '/space';
  static const groups = '/groups';
  static const avilableGroup = '/avilable_group';
  _Paths._();
}

abstract class _Names {
  static const profile = 'profile';
  static const editProfile = 'editProfile';
  static const reminder = 'reminder';
  static const splash = 'splash';
  static const onboarding = 'onboarding';
  static const questionnaire = 'questionnaire';
  static const startQuestionnaire = 'startQuestionnaire';
  static const cameraAnalysis = 'cameraAnalysis';
  static const startCamera = 'startCamera';
  static const assessmentResult = 'assessmentResult';
  static const otp = 'otp';
  static const navigation = 'navigation';
  static const home = 'home';
  static const specialists = 'specialists';
  static const specialistProfile = 'specialistProfile';
  static const success = 'success';
  static const words = 'words';
  static const srartwords = 'srartwords';
  static const breathing = 'breathing';
  static const srartexercise = 'srartexercise';
  static const payment = 'payment';
  static const plan = 'plan';
  static const auth = 'auth';
  static const forgetPassword = 'forget_password';
  static const login = 'login';
  static const signup = 'signup';
  static const changePassword = 'change_password';
  static const space = 'space';
  static const groups = 'groups';
  static const avilableGroup = 'avilable_group';
  _Names._();
}

abstract class Names {
  static const profile = _Names.profile;
  static const editProfile = _Names.editProfile;
  static const reminder = _Names.reminder;
  static const splash = _Names.splash;
  static const forgetPassword = _Names.forgetPassword;
  static const onboarding = _Names.onboarding;
  static const startQuestionnaire = _Names.startQuestionnaire;
  static const questionnaire = _Names.questionnaire;
  static const cameraAnalysis = _Names.cameraAnalysis;
  static const startCamera = _Names.startCamera;
  static const assessmentResult = _Names.assessmentResult;
  static const otp = _Names.otp;
  static const navigation = _Names.navigation;
  static const home = _Names.home;
  static const specialists = _Names.specialists;
  static const specialistProfile = _Names.specialistProfile;
  static const success = _Names.success;
  static const words = _Names.words;
  static const srartwords = _Names.srartwords;
  static const breathing = _Names.breathing;
  static const srartexercise = _Names.srartexercise;
  static const payment = _Names.payment;
  static const plan = _Names.plan;
  static const auth = _Names.auth;
  static const login = _Names.login;
  static const signup = _Names.signup;
  static const changePassword = _Names.changePassword;
  static const space = _Names.space;
  static const groups = _Names.groups;
  static const avilableGroup = _Names.avilableGroup;
  Names._();
}
